// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminAnimateList: typeof import('./../src/components/admin/animateList.vue')['default']
    AdminBreadcrumb: typeof import('./../src/components/admin/breadcrumb.vue')['default']
    AdminNotification: typeof import('./../src/components/admin/notification.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    RagDrawer: typeof import('./../src/components/rag/drawer.vue')['default']
    RagHistoryButton: typeof import('./../src/components/rag/historyButton.vue')['default']
    RagMain: typeof import('./../src/components/rag/main.vue')['default']
    RagMessage: typeof import('./../src/components/rag/message.vue')['default']
    RagMessageFrame: typeof import('./../src/components/rag/messageFrame.vue')['default']
    RagSide: typeof import('./../src/components/rag/side.vue')['default']
    RagUploadDocument: typeof import('./../src/components/rag/uploadDocument.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YButton: typeof import('./../src/components/y/button.vue')['default']
    YError: typeof import('./../src/components/y/error.vue')['default']
    YInput: typeof import('./../src/components/y/input.vue')['default']
    YLink: typeof import('./../src/components/y/link.vue')['default']
  }
}
