// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    LlmArea: typeof import('./../src/components/llm/area.vue')['default']
    LlmDrawer: typeof import('./../src/components/llm/drawer.vue')['default']
    LlmFinetune: typeof import('./../src/components/llm/finetune.vue')['default']
    LlmHistoryButton: typeof import('./../src/components/llm/historyButton.vue')['default']
    LlmMain: typeof import('./../src/components/llm/main.vue')['default']
    LlmMessage: typeof import('./../src/components/llm/message.vue')['default']
    LlmMessageFrame: typeof import('./../src/components/llm/messageFrame.vue')['default']
    LlmSide: typeof import('./../src/components/llm/side.vue')['default']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default']
    YButton: typeof import('./../src/components/y/button.vue')['default']
    YError: typeof import('./../src/components/y/error.vue')['default']
    YInput: typeof import('./../src/components/y/input.vue')['default']
    YLink: typeof import('./../src/components/y/link.vue')['default']
  }
}
